### ISSUE TITLE
Feature Plan

### ISSUE THREAD

**Issue by theolundqvist** [Bridgestars-Technologies-AB/bridgestars-web#40]
## Needed improvements due 10 of august to replace old site.
- [x] #54 (Since it is 99% done)
- [x] #56
- [x] #42
#### Following changes will be merged to prod instead of to dev. So these changes are just temporary and will not be used again.
- [x] Replace dashboard page with "Bridgestars will soon be available"
- [x] Replace texts "begin now" with "join the waitinglist" etc
- [x] Lastly, create a release and check if everything works in build, then publish

## game components
- [x] budlåda
- [ ] budstatus
- [ ] kort
- [ ] handrepresentation med bokstäver och siffror
- [ ] användare vid bord
- [ ] bord
- [ ] massa kort på rak, (min egen hand)
- [ ] listor med övningar
- [ ] lobby
- [ ] menu med (öva/spela budträning spelträning (dashboard??))

### Large
- [ ] User page, this is the same as overview but should be able to see other peoples page as well 
- [ ] user settings #48
- [ ] Game settings (cogwheel), language, bidding system and other settings
- [x] Chat UI (branch realtime-test)
- [x] Chat functional (branch realtime-test)

### Small/Quick
- [x] Dashboard should be open per default and not closed.
- [ ] Everything should be translated (account dropdown, chat, more?)
- [x] #62
- [x] #64
- [ ] Toasts can create a lot of distraction or stress for the elderly. Should we keep them? Make them stay longer? Change the position?, maybe on mobile the should be at the top of the screen.

## Not prioritized
- [x] #57 
- [ ] Video on homepage is a SEO problem, Largest Contentful Paint gets bad performance rating. Instead we should show image on load and then run short outro when pressing "play now" or when signing in

## Done
- [x] tooltips
- [x] profile dropdown: mina profil eller min sida, min uppgifter (här finns abonnemang, bild namn etc), logga ut. 
- [x] #41  
- [x] Side menu: small image and text on the right of it (nicer + does not interfere with profile page) #39 
- [x] click on image/name should lead to profile #39 
- [x] completely hide dash of not signed in #39 
- [x] #45
- [x] #46
- [x] #43

ps. for dropdowns [headless UI](https://headlessui.com/vue/menu) looks good

<br/>

-------------
### How to
1. start new issue for the request, edit/comment with issue number or click "convert to issue" on the right of the item, then when done check of item in list
<br/>
